export const Order = [
    {
        logo: "/navbar/Checkbox.svg",
        order_id: "#12435",
        customer_name: "Alyah Singh",
        email: "alyahsingh@example.com",
        mobile_no: "97453635",
        address: "C-3/1234, 2nd flr...",
        placed_date: "24 Oct, 2023",
        placed_time: "6 : 50 PM, Tue",
        total: "₹2340.00",
        delivery_status: "Dispatched",
        payment_status:"Unpaid",
        dispatch_date:"27 Oct, 2023",
        dispatch_time:"1 : 50 PM, Tue",
        courier_id :" #fedex1234",
        receive_date:"29 Oct, 2023",
        receive_time:"2:50 PM, Wed"
    },

    {
        logo: "/navbar/Checkbox.svg",
        order_id: "#12435",
        customer_name: "Alyah Singh",
        email: "alyahsingh@example.com",
        mobile_no: "97453635",
        address: "C-3/1234, 2nd flr...",
        placed_date: "24 Oct, 2023",
        placed_time: "6 : 50 PM, Tue",
        total: "₹2340.00",
        delivery_status: "Dispatched",
        payment_status:"Unpaid",
        dispatch_date:"27 Oct, 2023",
        dispatch_time:"1 : 50 PM, Tue",
        courier_id :" #fedex1234",
        receive_date:"29 Oct, 2023",
        receive_time:"2:50 PM, Wed"
    },
    {
        logo: "/navbar/Checkbox.svg",
        order_id: "#12435",
        customer_name: "Alyah Singh",
        email: "alyahsingh@example.com",
        mobile_no: "97453635",
        address: "C-3/1234, 2nd flr...",
        placed_date: "24 Oct, 2023",
        placed_time: "6 : 50 PM, Tue",
        total: "₹2340.00",
        delivery_status: "Dispatched",
        payment_status:"Unpaid",
        dispatch_date:"27 Oct, 2023",
        dispatch_time:"1 : 50 PM, Tue",
        courier_id :" #fedex1234",
        receive_date:"29 Oct, 2023",
        receive_time:"2:50 PM, Wed"
    },
    {
        logo: "/navbar/Checkbox.svg",
        order_id: "#12435",
        customer_name: "Alyah Singh",
        email: "alyahsingh@example.com",
        mobile_no: "97453635",
        address: "C-3/1234, 2nd flr...",
        placed_date: "24 Oct, 2023",
        placed_time: "6 : 50 PM, Tue",
        total: "₹2340.00",
        delivery_status: "Dispatched",
        payment_status:"Unpaid",
        dispatch_date:"27 Oct, 2023",
        dispatch_time:"1 : 50 PM, Tue",
        courier_id :" #fedex1234",
        receive_date:"29 Oct, 2023",
        receive_time:"2:50 PM, Wed"
    },

];
